app:
  character-set: [
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
    'A', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M',
    'N', 'P', 'Q', 'R', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
  ] # B, I, O and S are excluded as they can be misread as numbers
  code-length: 6
  code-ttl-seconds: 600
  maximum-validation-attempts: 3
