name: Build and Test

on: [push]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Installing JDK needs to come after checking out the repo because the action (setup-java) looks for the gradle wrapper files
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Run gradle `check` to lint source code and run unit tests
        run: ./gradlew --daemon check
      - name: Run gradle `testIntegration` to run integration tests
        run: ./gradlew --daemon testIntegration

      - name: Save logs on test failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Test logs
          path: |
            app/build/reports/tests/test
            domain/build/reports/tests/test
